#!/usr/bin/env php
<?php
require(__DIR__ . '/vendor/autoload.php');

if ($argc !== 3) {
    printf("USAGE: %s <day> <part>\n", $argv[0]);
    exit(0);
}

$class = "\Gussi\AOC2020\Day{$argv[1]}";

if (!class_exists($class)) {
    print("Solver for day {$argv[1]} not found...");
    exit(0);
}

$obj= new $class();
$solve = "part{$argv[2]}";
printf("Answer: %s\n", $obj->$solve());
